/************************************************
 * NAME	    : S5PV210.H
 * Version  : 31.3.2012
 ************************************************/
#ifndef __S5PV210_H__
#define __S5PV210_H__

#define 	_ISR_STARTADDRESS			0x3fff0000
#define 	pISR_EINT0 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x20))
#define 	pISR_EINT1 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x24))
#define 	pISR_EINT2 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x28))
#define 	pISR_EINT3 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x2c))
#define 	pISR_EINT4 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x30))
#define 	pISR_EINT5 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x34))
#define 	pISR_EINT6 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x38))
#define 	pISR_EINT7 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x3c))
#define 	pISR_EINT8 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x40))
#define 	pISR_EINT9 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x44))
#define 	pISR_EINT10		  			(*(unsigned *)(_ISR_STARTADDRESS+0x48))
#define 	pISR_EINT11		  			(*(unsigned *)(_ISR_STARTADDRESS+0x4c))
#define 	pISR_EINT12		  			(*(unsigned *)(_ISR_STARTADDRESS+0x50))
#define 	pISR_EINT13		  			(*(unsigned *)(_ISR_STARTADDRESS+0x54))
#define 	pISR_EINT14		  			(*(unsigned *)(_ISR_STARTADDRESS+0x58))
#define 	pISR_EINT15		  			(*(unsigned *)(_ISR_STARTADDRESS+0x5c)) 
#define 	pISR_EINT16_31  			(*(unsigned *)(_ISR_STARTADDRESS+0x60))
#define 	pISR_Reserved17 			(*(unsigned *)(_ISR_STARTADDRESS+0x64))
#define 	pISR_MDMA			  		(*(unsigned *)(_ISR_STARTADDRESS+0x68))
#define 	pISR_PDMA0 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x6c))
#define 	pISR_PDMA1 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x70))
#define 	pISR_TIMER0		  			(*(unsigned *)(_ISR_STARTADDRESS+0x74))
#define 	pISR_TIMER1		  			(*(unsigned *)(_ISR_STARTADDRESS+0x78))
#define 	pISR_TIMER2		  			(*(unsigned *)(_ISR_STARTADDRESS+0x7c))  
#define 	pISR_TIMER3		  			(*(unsigned *)(_ISR_STARTADDRESS+0x80))
#define 	pISR_TIMER4		  			(*(unsigned *)(_ISR_STARTADDRESS+0x84))
#define 	pISR_SYSTIMER	  			(*(unsigned *)(_ISR_STARTADDRESS+0x88))
#define 	pISR_WDT					(*(unsigned *)(_ISR_STARTADDRESS+0x8c))
#define 	pISR_RTC_ALARM  			(*(unsigned *)(_ISR_STARTADDRESS+0x90))
#define 	pISR_RTC_TICK	  			(*(unsigned *)(_ISR_STARTADDRESS+0x94))
#define 	pISR_GPIOINT				(*(unsigned *)(_ISR_STARTADDRESS+0x98))
#define 	pISR_FIMC3 		  			(*(unsigned *)(_ISR_STARTADDRESS+0x9c)) 
#define 	pISR_CORTEX0				(*(unsigned *)(_ISR_STARTADDRESS+0xa0))
#define 	pISR_CORTEX1				(*(unsigned *)(_ISR_STARTADDRESS+0xa4))
#define 	pISR_CORTEX2				(*(unsigned *)(_ISR_STARTADDRESS+0xa8))
#define 	pISR_CORTEX3				(*(unsigned *)(_ISR_STARTADDRESS+0xac)) 
#define 	pISR_CORTEX4				(*(unsigned *)(_ISR_STARTADDRESS+0xb0))
#define 	pISR_IEM_APC				(*(unsigned *)(_ISR_STARTADDRESS+0xb4))
#define 	pISR_IEM_IEC				(*(unsigned *)(_ISR_STARTADDRESS+0xb8))
#define 	pISR_Reserved39 			(*(unsigned *)(_ISR_STARTADDRESS+0xbc)) 
#define 	pISR_NFC					(*(unsigned *)(_ISR_STARTADDRESS+0xc0))
#define 	pISR_CFC					(*(unsigned *)(_ISR_STARTADDRESS+0xc4))
#define 	pISR_UART0 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xc8))
#define 	pISR_UART1 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xcc))
#define 	pISR_UART2 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xd0))
#define 	pISR_UART3 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xd4))
#define 	pISR_I2C					(*(unsigned *)(_ISR_STARTADDRESS+0xd8))
#define 	pISR_SPI0			  		(*(unsigned *)(_ISR_STARTADDRESS+0xdc))  
#define 	pISR_SPI1			  		(*(unsigned *)(_ISR_STARTADDRESS+0xe0))
#define 	pISR_SPI2			  		(*(unsigned *)(_ISR_STARTADDRESS+0xe4))
#define 	pISR_AUDIO 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xe8))
#define 	pISR_I2C_PMIC	  			(*(unsigned *)(_ISR_STARTADDRESS+0xec))
#define 	pISR_I2C_HDMI	  			(*(unsigned *)(_ISR_STARTADDRESS+0xf0))
#define 	pISR_HSIRX 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xf4))
#define 	pISR_HSITX 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xf8))
#define 	pISR_UHOST 		  			(*(unsigned *)(_ISR_STARTADDRESS+0xfc))
#define 	pISR_OTG					(*(unsigned *)(_ISR_STARTADDRESS+0x100))
#define 	pISR_MSM					(*(unsigned *)(_ISR_STARTADDRESS+0x104))
#define 	pISR_HSMMC0		  			(*(unsigned *)(_ISR_STARTADDRESS+0x108))
#define 	pISR_HSMMC1		  			(*(unsigned *)(_ISR_STARTADDRESS+0x10c))       
#define 	pISR_HSMMC2		  			(*(unsigned *)(_ISR_STARTADDRESS+0x110))
#define 	pISR_MIPI_CSI	  			(*(unsigned *)(_ISR_STARTADDRESS+0x114))
#define 	pISR_MIPI_DSI	  			(*(unsigned *)(_ISR_STARTADDRESS+0x118))
#define 	pISR_ONENAND_AU 			(*(unsigned *)(_ISR_STARTADDRESS+0x11c))
#define 	pISR_LCD0			    	(*(unsigned *)(_ISR_STARTADDRESS+0x120))                      		
#define 	pISR_LCD1			    	(*(unsigned *)(_ISR_STARTADDRESS+0x124))
#define 	pISR_LCD2			   	 	(*(unsigned *)(_ISR_STARTADDRESS+0x128))
#define 	pISR_LCD3			    	(*(unsigned *)(_ISR_STARTADDRESS+0x12c))
#define		pISR_ROTATOR		  		(*(unsigned *)(_ISR_STARTADDRESS+0x130))
#define 	pISR_FIMC_A		    		(*(unsigned *)(_ISR_STARTADDRESS+0x134))
#define 	pISR_FIMC_B		    		(*(unsigned *)(_ISR_STARTADDRESS+0x138))
#define 	pISR_FIMC_C		    		(*(unsigned *)(_ISR_STARTADDRESS+0x13c))
#define 	pISR_JPEG			    	(*(unsigned *)(_ISR_STARTADDRESS+0x140))
#define 	pISR_2D				  	  	(*(unsigned *)(_ISR_STARTADDRESS+0x144))
#define 	pISR_3D				 	   	(*(unsigned *)(_ISR_STARTADDRESS+0x148))
#define 	pISR_MIXER 		    		(*(unsigned *)(_ISR_STARTADDRESS+0x14c))
#define 	pISR_HDMI			    	(*(unsigned *)(_ISR_STARTADDRESS+0x150))
#define 	pISR_HDMI_I2C	    		(*(unsigned *)(_ISR_STARTADDRESS+0x154))
#define 	pISR_MFC				  	(*(unsigned *)(_ISR_STARTADDRESS+0x158))
#define 	pISR_TVENC 		    		(*(unsigned *)(_ISR_STARTADDRESS+0x15c))
#define 	pISR_I2S0			    	(*(unsigned *)(_ISR_STARTADDRESS+0x160))
#define 	pISR_I2S1			    	(*(unsigned *)(_ISR_STARTADDRESS+0x164))
#define 	pISR_I2S2			    	(*(unsigned *)(_ISR_STARTADDRESS+0x168))
#define 	pISR_AC97			    	(*(unsigned *)(_ISR_STARTADDRESS+0x16c))
#define 	pISR_PCM0			    	(*(unsigned *)(_ISR_STARTADDRESS+0x170))
#define 	pISR_PCM1			    	(*(unsigned *)(_ISR_STARTADDRESS+0x174))
#define 	pISR_SPDIF 		    		(*(unsigned *)(_ISR_STARTADDRESS+0x178))
#define 	pISR_ADC				  	(*(unsigned *)(_ISR_STARTADDRESS+0x17c))
#define 	pISR_PENDN 		    		(*(unsigned *)(_ISR_STARTADDRESS+0x180))
#define 	pISR_KEYPAD		    		(*(unsigned *)(_ISR_STARTADDRESS+0x184))
#define 	pISR_Reserved90   			(*(unsigned *)(_ISR_STARTADDRESS+0x188))
#define 	pISR_HASH			    	(*(unsigned *)(_ISR_STARTADDRESS+0x18c))
#define 	pISR_FEEDCTRL	    		(*(unsigned *)(_ISR_STARTADDRESS+0x190))
#define 	pISR_PCM2			    	(*(unsigned *)(_ISR_STARTADDRESS+0x194))
#define 	pISR_SDM_IRQ		  		(*(unsigned *)(_ISR_STARTADDRESS+0x198))
#define 	pISR_SMD_FIQ		  		(*(unsigned *)(_ISR_STARTADDRESS+0x19c))
#define 	pISR_IPC				  	(*(unsigned *)(_ISR_STARTADDRESS+0x1a0))
#define 	pISR_HOSTIF		    		(*(unsigned *)(_ISR_STARTADDRESS+0x1a4))
#define 	pISR_HSMMC3		    		(*(unsigned *)(_ISR_STARTADDRESS+0x1a8))
#define 	pISR_CEC				  	(*(unsigned *)(_ISR_STARTADDRESS+0x1ac)) 
#define 	pISR_TSI				  	(*(unsigned *)(_ISR_STARTADDRESS+0x1b0))
#define 	pISR_MDNIE0		    		(*(unsigned *)(_ISR_STARTADDRESS+0x1b4))
#define 	pISR_MDNIE1		    		(*(unsigned *)(_ISR_STARTADDRESS+0x1b8))
#define 	pISR_MDNIE2		    		(*(unsigned *)(_ISR_STARTADDRESS+0x1bc))
#define 	pISR_MDNIE3		  			(*(unsigned *)(_ISR_STARTADDRESS+0x1c0))
#define 	pISR_ADC1			 		(*(unsigned *)(_ISR_STARTADDRESS+0x1c4))
#define 	pISR_PENDN1		  			(*(unsigned *)(_ISR_STARTADDRESS+0x1c8))

// TIMER
#define		PWMTIMER_BASE				(0xE2500000)
#define		TCFG0    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x00)) )
#define		TCFG1    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x04)) )
#define		TCON     			 		( *((volatile unsigned long *)(PWMTIMER_BASE+0x08)) )
#define		TCNTB0    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x0C)) )
#define		TCMPB0    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x10)) )
#define		TCNTO0    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x14)) )
#define		TCNTB1    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x18)) )
#define		TCMPB1    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x1C)) )
#define		TCNTO1    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x20)) )
#define		TCNTB2    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x24)) )
#define		TCMPB2    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x28)) )
#define		TCNTO2    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x2C)) )
#define		TCNTB3    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x30)) )
#define		TCMPB3    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x34)) )
#define		TCNTO3   			 		( *((volatile unsigned long *)(PWMTIMER_BASE+0x38)) )
#define		TCNTB4   			 		( *((volatile unsigned long *)(PWMTIMER_BASE+0x3C)) )
#define		TCNTO4    					( *((volatile unsigned long *)(PWMTIMER_BASE+0x40)) )
#define		TINT_CSTAT 					( *((volatile unsigned long *)(PWMTIMER_BASE+0x44)) )

// Interrupt
#define 	VIC0_BASE					(0xF2000000)
#define 	VIC1_BASE					(0xF2100000)
#define 	VIC2_BASE					(0xF2200000)
#define 	VIC3_BASE					(0xF2300000)
// VIC0
#define		VIC0IRQSTATUS				( *((volatile unsigned long *)(VIC0_BASE + 0x00)) )
#define		VIC0FIQSTATUS				( *((volatile unsigned long *)(VIC0_BASE + 0x04)) )
#define		VIC0RAWINTR					( *((volatile unsigned long *)(VIC0_BASE + 0x08)) )
#define		VIC0INTSELECT				( *((volatile unsigned long *)(VIC0_BASE + 0x0c)) )
#define		VIC0INTENABLE				( *((volatile unsigned long *)(VIC0_BASE + 0x10)) )
#define		VIC0INTENCLEAR				( *((volatile unsigned long *)(VIC0_BASE + 0x14)) )
#define		VIC0SOFTINT					( *((volatile unsigned long *)(VIC0_BASE + 0x18)) )
#define		VIC0SOFTINTCLEAR			( *((volatile unsigned long *)(VIC0_BASE + 0x1c)) )
#define		VIC0PROTECTION				( *((volatile unsigned long *)(VIC0_BASE + 0x20)) )
#define		VIC0SWPRIORITYMASK			( *((volatile unsigned long *)(VIC0_BASE + 0x24)) )
#define		VIC0PRIORITYDAISY			( *((volatile unsigned long *)(VIC0_BASE + 0x28)) )
#define 	VIC0VECTADDR				(VIC0_BASE + 0x100)
#define 	VIC0VECPRIORITY				( *((volatile unsigned long *)(VIC0_BASE + 0x200)) )
#define 	VIC0ADDR					( *((volatile unsigned long *)(VIC0_BASE + 0xf00)) )
#define 	VIC0PERID0					( *((volatile unsigned long *)(VIC0_BASE + 0xfe0)) )
#define 	VIC0PERID1					( *((volatile unsigned long *)(VIC0_BASE + 0xfe4)) )
#define 	VIC0PERID2					( *((volatile unsigned long *)(VIC0_BASE + 0xfe8)) )
#define 	VIC0PERID3					( *((volatile unsigned long *)(VIC0_BASE + 0xfec)) )
#define 	VIC0PCELLID0				( *((volatile unsigned long *)(VIC0_BASE + 0xff0)) )
#define 	VIC0PCELLID1				( *((volatile unsigned long *)(VIC0_BASE + 0xff4)) )
#define 	VIC0PCELLID2				( *((volatile unsigned long *)(VIC0_BASE + 0xff8)) )
#define 	VIC0PCELLID3				( *((volatile unsigned long *)(VIC0_BASE + 0xffc)) )
// VIC1
#define		VIC1IRQSTATUS				( *((volatile unsigned long *)(VIC1_BASE + 0x00)) )
#define		VIC1FIQSTATUS				( *((volatile unsigned long *)(VIC1_BASE + 0x04)) )
#define		VIC1RAWINTR					( *((volatile unsigned long *)(VIC1_BASE + 0x08)) )
#define		VIC1INTSELECT				( *((volatile unsigned long *)(VIC1_BASE + 0x0c)) )
#define		VIC1INTENABLE				( *((volatile unsigned long *)(VIC1_BASE + 0x10)) )
#define		VIC1INTENCLEAR				( *((volatile unsigned long *)(VIC1_BASE + 0x14)) )
#define		VIC1SOFTINT					( *((volatile unsigned long *)(VIC1_BASE + 0x18)) )
#define		VIC1SOFTINTCLEAR			( *((volatile unsigned long *)(VIC1_BASE + 0x1c)) )
#define		VIC1PROTECTION				( *((volatile unsigned long *)(VIC1_BASE + 0x20)) )
#define		VIC1SWPRIORITYMASK			( *((volatile unsigned long *)(VIC1_BASE + 0x24)) )
#define		VIC1PRIORITYDAISY			( *((volatile unsigned long *)(VIC1_BASE + 0x28)) )
#define 	VIC1VECTADDR				(VIC1_BASE + 0x100)
#define 	VIC1VECPRIORITY				( *((volatile unsigned long *)(VIC1_BASE + 0x200)) )
#define 	VIC1ADDR					( *((volatile unsigned long *)(VIC1_BASE + 0xf00)) )
#define 	VIC1PERID0					( *((volatile unsigned long *)(VIC1_BASE + 0xfe0)) )
#define 	VIC1PERID1					( *((volatile unsigned long *)(VIC1_BASE + 0xfe4)) )
#define 	VIC1PERID2					( *((volatile unsigned long *)(VIC1_BASE + 0xfe8)) )
#define 	VIC1PERID3					( *((volatile unsigned long *)(VIC1_BASE + 0xfec)) )
#define 	VIC1PCELLID0				( *((volatile unsigned long *)(VIC1_BASE + 0xff0)) )
#define 	VIC1PCELLID1				( *((volatile unsigned long *)(VIC1_BASE + 0xff4)) )
#define 	VIC1PCELLID2				( *((volatile unsigned long *)(VIC1_BASE + 0xff8)) )
#define 	VIC1PCELLID3				( *((volatile unsigned long *)(VIC1_BASE + 0xffc)) )
// VIC2
#define		VIC2IRQSTATUS				( *((volatile unsigned long *)(VIC2_BASE + 0x00)) )
#define		VIC2FIQSTATUS				( *((volatile unsigned long *)(VIC2_BASE + 0x04)) )
#define		VIC2RAWINTR					( *((volatile unsigned long *)(VIC2_BASE + 0x08)) )
#define		VIC2INTSELECT				( *((volatile unsigned long *)(VIC2_BASE + 0x0c)) )
#define		VIC2INTENABLE				( *((volatile unsigned long *)(VIC2_BASE + 0x10)) )
#define		VIC2INTENCLEAR				( *((volatile unsigned long *)(VIC2_BASE + 0x14)) )
#define		VIC2SOFTINT					( *((volatile unsigned long *)(VIC2_BASE + 0x18)) )
#define		VIC2SOFTINTCLEAR			( *((volatile unsigned long *)(VIC2_BASE + 0x1c)) )
#define		VIC2PROTECTION				( *((volatile unsigned long *)(VIC2_BASE + 0x20)) )
#define		VIC2SWPRIORITYMASK			( *((volatile unsigned long *)(VIC2_BASE + 0x24)) )
#define		VIC2PRIORITYDAISY			( *((volatile unsigned long *)(VIC2_BASE + 0x28)) )
#define 	VIC2VECTADDR				(VIC2_BASE + 0x100)
#define 	VIC2VECPRIORITY				( *((volatile unsigned long *)(VIC2_BASE + 0x200)) )
#define 	VIC2ADDR					( *((volatile unsigned long *)(VIC2_BASE + 0xf00)) )
#define 	VIC2PERID0					( *((volatile unsigned long *)(VIC2_BASE + 0xfe0)) )
#define 	VIC2PERID1					( *((volatile unsigned long *)(VIC2_BASE + 0xfe4)) )
#define 	VIC2PERID2					( *((volatile unsigned long *)(VIC2_BASE + 0xfe8)) )
#define 	VIC2PERID3					( *((volatile unsigned long *)(VIC2_BASE + 0xfec)) )
#define 	VIC2PCELLID0				( *((volatile unsigned long *)(VIC2_BASE + 0xff0)) )
#define 	VIC2PCELLID1				( *((volatile unsigned long *)(VIC2_BASE + 0xff4)) )
#define 	VIC2PCELLID2				( *((volatile unsigned long *)(VIC2_BASE + 0xff8)) )
#define 	VIC2PCELLID3				( *((volatile unsigned long *)(VIC2_BASE + 0xffc)) )
// VIC3
#define		VIC3IRQSTATUS				( *((volatile unsigned long *)(VIC3_BASE + 0x00)) )
#define	 	VIC3FIQSTATUS				( *((volatile unsigned long *)(VIC3_BASE + 0x04)) )
#define	 	VIC3RAWINTR					( *((volatile unsigned long *)(VIC3_BASE + 0x08)) )
#define	 	VIC3INTSELECT				( *((volatile unsigned long *)(VIC3_BASE + 0x0c)) )
#define	 	VIC3INTENABLE				( *((volatile unsigned long *)(VIC3_BASE + 0x10)) )
#define	 	VIC3INTENCLEAR				( *((volatile unsigned long *)(VIC3_BASE + 0x14)) )
#define	 	VIC3SOFTINT					( *((volatile unsigned long *)(VIC3_BASE + 0x18)) )
#define	 	VIC3SOFTINTCLEAR			( *((volatile unsigned long *)(VIC3_BASE + 0x1c)) )
#define	 	VIC3PROTECTION				( *((volatile unsigned long *)(VIC3_BASE + 0x20)) )
#define	 	VIC3SWPRIORITYMASK			( *((volatile unsigned long *)(VIC3_BASE + 0x24)) )
#define	 	VIC3PRIORITYDAISY			( *((volatile unsigned long *)(VIC3_BASE + 0x28)) )
#define 	VIC3VECTADDR				(VIC3_BASE + 0x100)
#define 	VIC3VECPRIORITY				( *((volatile unsigned long *)(VIC3_BASE + 0x200)) )
#define 	VIC3ADDR					( *((volatile unsigned long *)(VIC3_BASE + 0xf00)) )
#define 	VIC3PERID0					( *((volatile unsigned long *)(VIC3_BASE + 0xfe0)) )
#define 	VIC3PERID1					( *((volatile unsigned long *)(VIC3_BASE + 0xfe4)) )
#define 	VIC3PERID2					( *((volatile unsigned long *)(VIC3_BASE + 0xfe8)) )
#define 	VIC3PERID3					( *((volatile unsigned long *)(VIC3_BASE + 0xfec)) )
#define 	VIC3PCELLID0				( *((volatile unsigned long *)(VIC3_BASE + 0xff0)) )
#define 	VIC3PCELLID1				( *((volatile unsigned long *)(VIC3_BASE + 0xff4)) )
#define 	VIC3PCELLID2				( *((volatile unsigned long *)(VIC3_BASE + 0xff8)) )
#define 	VIC3PCELLID3				( *((volatile unsigned long *)(VIC3_BASE + 0xffc)) )

// UART相关寄存器
#define 	GPA0CON 					( *((volatile unsigned long *)0xE0200000) )		
#define 	GPA1CON 					( *((volatile unsigned long *)0xE0200020) )
#define 	ULCON0 						( *((volatile unsigned long *)0xE2900000) )		
#define 	UCON0 						( *((volatile unsigned long *)0xE2900004) )
#define 	UFCON0 						( *((volatile unsigned long *)0xE2900008) )
#define 	UMCON0 						( *((volatile unsigned long *)0xE290000C) )
#define 	UTRSTAT0 					( *((volatile unsigned long *)0xE2900010) )
#define 	UERSTAT0 					( *((volatile unsigned long *)0xE2900014) )
#define 	UFSTAT0 					( *((volatile unsigned long *)0xE2900018) )
#define 	UMSTAT0 					( *((volatile unsigned long *)0xE290001C) )
#define 	UTXH0 						( *((volatile unsigned long *)0xE2900020) )
#define 	URXH0 						( *((volatile unsigned long *)0xE2900024) )
#define 	UBRDIV0 					( *((volatile unsigned long *)0xE2900028) )
#define 	UDIVSLOT0 					( *((volatile unsigned long *)0xE290002C) )
#define 	UINTP 						( *((volatile unsigned long *)0xE2900030) )
#define 	UINTSP 						( *((volatile unsigned long *)0xE2900034) )
#define 	UINTM 						( *((volatile unsigned long *)0xE2900038) )

#define 	UART_UBRDIV_VAL				35
#define 	UART_UDIVSLOT_VAL			0x1

// 时钟相关寄存器
#define 	APLL_LOCK 					( *((volatile unsigned long *)0xE0100000) )		
#define 	MPLL_LOCK 					( *((volatile unsigned long *)0xE0100008) )
#define 	APLL_CON0 					( *((volatile unsigned long *)0xE0100100) )
#define 	APLL_CON1 					( *((volatile unsigned long *)0xE0100104) )
#define 	MPLL_CON 					( *((volatile unsigned long *)0xE0100108) )
#define 	CLK_SRC0 					( *((volatile unsigned long *)0xE0100200) )
#define 	CLK_SRC1 					( *((volatile unsigned long *)0xE0100204) )
#define 	CLK_SRC2 					( *((volatile unsigned long *)0xE0100208) )
#define 	CLK_SRC3 					( *((volatile unsigned long *)0xE010020c) )
#define 	CLK_SRC4 					( *((volatile unsigned long *)0xE0100210) )
#define 	CLK_SRC5 					( *((volatile unsigned long *)0xE0100214) )
#define 	CLK_SRC6 					( *((volatile unsigned long *)0xE0100218) )
#define 	CLK_SRC_MASK0 				( *((volatile unsigned long *)0xE0100280) )
#define 	CLK_SRC_MASK1 				( *((volatile unsigned long *)0xE0100284) )
#define 	CLK_DIV0 					( *((volatile unsigned long *)0xE0100300) )
#define 	CLK_DIV1 					( *((volatile unsigned long *)0xE0100304) )
#define 	CLK_DIV2 					( *((volatile unsigned long *)0xE0100308) )
#define 	CLK_DIV3 					( *((volatile unsigned long *)0xE010030c) )
#define 	CLK_DIV4 					( *((volatile unsigned long *)0xE0100310) )
#define 	CLK_DIV5 					( *((volatile unsigned long *)0xE0100314) )
#define 	CLK_DIV6 					( *((volatile unsigned long *)0xE0100318) )
#define 	CLK_DIV7 					( *((volatile unsigned long *)0xE010031c) )

#define 	CLK_DIV0_MASK				0x7fffffff
#define 	APLL_MDIV       			0x7d
#define 	APLL_PDIV       			0x3
#define 	APLL_SDIV      	 			0x1
#define 	MPLL_MDIV					0x29b
#define 	MPLL_PDIV					0xc
#define 	MPLL_SDIV					0x1
#define 	set_pll(mdiv, pdiv, sdiv)	(1<<31 | mdiv<<16 | pdiv<<8 | sdiv)
#define 	APLL_VAL					set_pll(APLL_MDIV,APLL_PDIV,APLL_SDIV)
#define 	MPLL_VAL					set_pll(MPLL_MDIV,MPLL_PDIV,MPLL_SDIV)

// RTC
#define 	RTC_BASE	 				(0xE2800000)
#define		rINTP        				( *((volatile unsigned long *)(RTC_BASE + 0x30)) )
#define		rRTCCON    	 				( *((volatile unsigned long *)(RTC_BASE + 0x40)) )
#define		rTICCNT    	 				( *((volatile unsigned long *)(RTC_BASE + 0x44)) )
#define		rRTCALM    	 				( *((volatile unsigned long *)(RTC_BASE + 0x50)) )
#define		rALMSEC    	 				( *((volatile unsigned long *)(RTC_BASE + 0x54)) )
#define		rALMMIN    	 				( *((volatile unsigned long *)(RTC_BASE + 0x58)) )
#define		rALMHOUR  	 				( *((volatile unsigned long *)(RTC_BASE + 0x5c)) )
#define		rALMDATE     				( *((volatile unsigned long *)(RTC_BASE + 0x60)) )
#define		rALMMON    	 				( *((volatile unsigned long *)(RTC_BASE + 0x64)) )
#define		rALMYEAR  	 				( *((volatile unsigned long *)(RTC_BASE + 0x68)) )
#define		rRTCRST      				( *((volatile unsigned long *)(RTC_BASE + 0x6c)) )
#define		rBCDSEC    	 				( *((volatile unsigned long *)(RTC_BASE + 0x70)) )
#define		rBCDMIN   	 				( *((volatile unsigned long *)(RTC_BASE + 0x74)) )
#define		rBCDHOUR     				( *((volatile unsigned long *)(RTC_BASE + 0x78)) )
#define		rBCDDATE     				( *((volatile unsigned long *)(RTC_BASE + 0x7c)) )
#define		rBCDDAY      				( *((volatile unsigned long *)(RTC_BASE + 0x80)) )
#define		rBCDMON      				( *((volatile unsigned long *)(RTC_BASE + 0x84)) )
#define		rBCDYEAR     				( *((volatile unsigned long *)(RTC_BASE + 0x88)) )
#define		rCURTICCNT   				( *((volatile unsigned long *)(RTC_BASE + 0x90)) )
#define		rRTCLVD    	 				( *((volatile unsigned long *)(RTC_BASE + 0x94)) )
#define 	FROM_BCD(n)		 			((((n) >> 4) * 10) + ((n) & 0xf))
#define 	TO_BCD(n)		 			((((n) / 10) << 4) | ((n) % 10))

// LCD
#define 	GPF0CON						(*(volatile unsigned long *)0xE0200120)
#define 	GPF1CON						(*(volatile unsigned long *)0xE0200140)
#define 	GPF2CON						(*(volatile unsigned long *)0xE0200160)
#define 	GPF3CON						(*(volatile unsigned long *)0xE0200180)
#define 	GPD0CON						(*(volatile unsigned long *)0xE02000A0)
#define 	GPD0DAT						(*(volatile unsigned long *)0xE02000A4)
#define 	CLK_SRC1					(*(volatile unsigned long *)0xe0100204)
#define 	CLK_DIV1					(*(volatile unsigned long *)0xe0100304)
#define 	DISPLAY_CONTROL				(*(volatile unsigned long *)0xe0107008)
#define 	VIDCON0						(*(volatile unsigned long *)0xF8000000)
#define 	VIDCON1						(*(volatile unsigned long *)0xF8000004)
#define 	VIDTCON2					(*(volatile unsigned long *)0xF8000018)
#define 	WINCON0 					(*(volatile unsigned long *)0xF8000020)
#define 	WINCON2 					(*(volatile unsigned long *)0xF8000028)
#define 	SHADOWCON 					(*(volatile unsigned long *)0xF8000034)
#define 	VIDOSD0A 					(*(volatile unsigned long *)0xF8000040)
#define 	VIDOSD0B 					(*(volatile unsigned long *)0xF8000044)
#define 	VIDOSD0C 					(*(volatile unsigned long *)0xF8000048)
#define 	VIDW00ADD0B0 				(*(volatile unsigned long *)0xF80000A0)
#define 	VIDW00ADD1B0 				(*(volatile unsigned long *)0xF80000D0)
#define 	VIDTCON0 					(*(volatile unsigned long *)0xF8000010)
#define 	VIDTCON1 					(*(volatile unsigned long *)0xF8000014)

// touch
#define 	GPH1CON 					(*(volatile unsigned long *)0xE0200C20)
#define 	GPH1DAT 					(*(volatile unsigned long *)0xE0200C24)
#define 	GPH1PUD 					(*(volatile unsigned long *)0xE0200C28)

#endif /*__S5PV210_H__*/
